[package]
name = "bridge-derive"
version = "0.1.0"
authors = ["Broxus team"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
darling = "0.13"
quote = "1.0"
proc-macro2 = "1.0"
syn = { version = "1.0", features = ["full"] }
