[package]
name = "token-proxy"
version = "0.1.0"
authors = ["Broxus team"]
edition = "2021"

[features]
no-entrypoint = []
test-bpf = []

[dependencies]
bincode = "1.3"
borsh = "0.9"
enum-as-inner = "0.3"
solana-program = "1.9"
thiserror = "1.0"
spl-token = {version = "3.2", features = ["no-entrypoint"]}
spl-associated-token-account = {version = "1.0", features = ["no-entrypoint"]}

bridge-derive = { path = "../bridge-derive" }
bridge-utils = { path = "../bridge-utils" }
round-loader = { path = "../round-loader", features = ["no-entrypoint"] }

[dev-dependencies]
solana-program-test = "1.9"
solana-sdk = "1.9"

[lib]
crate-type = ["cdylib", "lib"]
