[package]
name = "token-proxy"
version = "0.1.0"
authors = ["Broxus team"]
edition = "2021"

[features]
no-entrypoint = []
test-bpf = []

[dependencies]
arrayref = "0.3"
bincode = "1.3"
borsh = "0.9"
solana-program = "1.9"
thiserror = "1.0"
spl-token = "3.2"
round-loader = {path = "../round-loader"}

[lib]
crate-type = ["cdylib", "lib"]
