[package]
name = "bridge-utils"
version = "0.1.0"
authors = ["Broxus team"]
edition = "2021"

[dependencies]
bincode = "1.3"
borsh = "0.9"
serde = { version = "1.0", features = ["derive"] }
solana-program = "1.10"
spl-token = "3.2"
spl-associated-token-account = "1.0"
