[package]
name = "bridge-utils"
version = "0.1.0"
authors = ["Broxus team"]
edition = "2021"

[dependencies]
bincode = "1.3"
solana-program = "1.9"
spl-token = "3.2"
spl-associated-token-account = "1.0"
