[package]
name = "round-loader"
version = "0.1.0"
authors = ["Broxus team"]
edition = "2021"

[features]
no-entrypoint = []
test-bpf = ["bindings"]
bindings = ["ton_types", "no-entrypoint"]
wasm = ["no-entrypoint", "wasm-bindgen"]

[dependencies]
bincode = "1.3"
borsh = "0.9"
serde = { version = "1.0", features = ["derive"] }
solana-program = "1.10"
ton_types = { git = "https://github.com/broxus/ton-labs-types", optional = true }
thiserror = "1.0"
wasm-bindgen = { version = "0.2.79", features = ["serde-serialize"], optional = true }

bridge-derive = { path = "../bridge-derive" }
bridge-utils = { path = "../bridge-utils" }

[dev-dependencies]
solana-program-test = "1.10"
solana-sdk = "1.10"

[lib]
crate-type = ["cdylib", "lib"]
